name = "daily-joke-email"
compatibility_date = "2024-01-01"
main = "index.js"

[triggers]
crons = ["0 23 * * *"]  # UTC时间23点（北京时间第二天7点）

[vars]
SENDER_EMAIL = "a@qxz.qzz.io"  # 替换为你的域名
RECIPIENT_EMAIL = "ljx20110119@qq.com"  # 替换为你的邮箱
